app/model/index.ts

https://www.pivotaltracker.com/story/show/179808505

Updated import method to the replace the DID document

---

app/components/ApprovalControls/ApprovalControls.tsx
app/hooks/usePendingCredential.ts
app/store/slices/credentialFoyer.ts

Addresses issue #73
PT Story: https://www.pivotaltracker.com/story/show/180130529

Fixed approval controls and added duplicate credential handling

---

android/app/src/main/res/values/strings.xml
app.json
app/navigation/SettingsNavigation/SettingsNavigation.tsx
app/navigation/SetupNavigation/SetupNavigation.tsx
app/screens/LoginScreen/LoginScreen.tsx
ios/eduwallet/Info.plist
package.json

The app display name was previously `edu-wallet` but this PR updates it to `EDU Wallet`

Updated app display name

---

app/data/issuerAuth.ts
app/data/issuerDid.ts
app/lib/present.ts
app/lib/registry.ts
app/lib/request.ts
app/lib/validate.ts

PT Stories:
* https://www.pivotaltracker.com/story/show/179924376
* https://www.pivotaltracker.com/story/show/180578496
* https://www.pivotaltracker.com/story/show/180579086
You can test the credential deep link request flow (including OIDC auth) with the instructions in PR #58

Added OIDC auth config for xPro, Georgia Tech, and McMaster

---

app/components/CredentialCard/CredentialCard.tsx

PT Story: [[BUG] Date Handling and Display on Credential Card](https://www.pivotaltracker.com/story/show/180798957)

Fixed dating formating for the credential card

---

app/components/PasswordInput/PasswordInput.tsx
app/navigation/SetupNavigation/SetupNavigation.tsx

PT Story: [[FEATURE] On wallet setup, set initial focus to Password field](https://www.pivotaltracker.com/story/show/180694856)

Implemented password input auto focus

---

app/data/issuerAuth.ts

This PR includes the correct scope for McMaster's OIDC config entry

Fixed McMaster OIDC config scope

---

android/app/build.gradle
app/hooks/useRequestCredential.ts
app/lib/encode.ts
app/lib/request.ts
app/navigation/AppNavigation/AppNavigation.tsx

Changes:
* Updated credential request `challenge` param to be optional
* Added query param encoding for deep links containing reserved characters
* Added additional error handling for invalid credential requests
* Fixed occasional splash screen stall bug

Fixed deep link bugs

---

app/screens/QRScreen/QRScreen.styles.ts

PT Story: [[BUG] Camera control on Add Credential overlaps text](https://www.pivotaltracker.com/story/show/180722691)

Fixed QR code instructions overlap styling

---

app/components/LoadingIndicator/LoadingIndicator.tsx

Fixed LoadingIndicator.tsx lint issue

---

app/components/VerificationCard/VerificationCard.styles.ts
app/components/VerificationCard/VerificationCard.tsx
app/components/VerificationStatusCard/VerificationStatusCard.d.ts
app/components/VerificationStatusCard/VerificationStatusCard.styles.ts
app/components/VerificationStatusCard/VerificationStatusCard.tsx
app/components/index.ts
app/hooks/useVerifyCredential.ts
app/navigation/RootNavigation/RootNavigation.d.tsx
app/navigation/RootNavigation/RootNavigation.tsx
app/navigation/index.ts
app/screens/ApproveCredentialScreen/ApproveCredentialScreen.tsx
app/screens/CredentialScreen/CredentialScreen.tsx
app/screens/VerificationStatusScreen/VerificationStatusScreen.d.ts
app/screens/VerificationStatusScreen/VerificationStatusScreen.styles.ts
app/screens/VerificationStatusScreen/VerificationStatusScreen.tsx
app/screens/index.ts

GitHub Issue - #98 
PT Story - https://www.pivotaltracker.com/story/show/180955122
| <img width="520" alt="Screen Shot 2022-01-19 at 8 13 28 PM" src="https://user-images.githubusercontent.com/11971291/150265978-ee3500cb-88d3-4c00-a0cc-a91ce82c134d.png"> | <img width="520" alt="Screen Shot 2022-01-19 at 8 12 05 PM" src="https://user-images.githubusercontent.com/11971291/150266040-e3eb525c-4df1-468e-9dd8-02a1fdeecfae.png"> |
| --- | --- |

Added verification status screen

---

app/components/CredentialCard/CredentialCard.tsx

GitHub Issue -  #102 
PT Story - https://www.pivotaltracker.com/story/show/180973048

Fixed conditional date display logic

---

app/components/ApprovalControls/ApprovalControls.tsx
app/components/CredentialItem/CredentialItem.tsx

PT Story - [[BUG] Unable to press 'Accept' button while in TalkBack mode](https://www.pivotaltracker.com/story/show/180879797)

Fixed accessibility for credential approval controls

---

package-lock.json
package.json

Update vc-js dep (fix protocol error).

---

app/navigation/SettingsNavigation/SettingsNavigation.tsx
ios/Podfile.lock
package-lock.json
package.json

adds version and build to about screen

---

.gitignore
android/gradle.properties
android/gradle/wrapper/gradle-wrapper.properties

Upgrades needed to sign/publish to Google Play store.

Update to gradle 6.9 dep.

---

app/data/issuerAuth.ts
app/data/issuerDid.ts

Adds default oidc issuer for playground

---

android/app/build.gradle
android/app/src/main/AndroidManifest.xml
app/lib/present.ts
app/lib/request.ts
app/navigation/AppNavigation/AppNavigation.tsx

Fixes the Georgia Tech side of #125

Fixed credential requests for Android

---

android/app/src/main/AndroidManifest.xml
android/settings.gradle
app/hooks/useRequestCredential.ts
app/lib/request.ts

(Also changes the gradle project name to `eduWallet`.)

Add diagnostics.

---

app/components/CredentialItem/CredentialItem.styles.tsx
app/screens/AddScreen/AddScreen.styles.tsx
app/screens/ApproveCredentialsScreen/ApproveCredentialsScreen.styles.ts
app/screens/ApproveCredentialsScreen/ApproveCredentialsScreen.tsx
app/screens/HomeScreen/HomeScreen.styles.tsx
app/screens/HomeScreen/HomeScreen.tsx
app/screens/ShareHomeScreen/ShareHomeScreen.styles.ts
app/screens/ShareHomeScreen/ShareHomeScreen.tsx
app/styles/mixins.ts

There were a couple of spacing issues that have been fixed to match the original designs.
Adobe XD Designs - https://xd.adobe.com/view/6f1463ae-cefd-4b5e-8641-474ab7880353-3a47
| Before | After |
| --- | --- |
| ![Screen Shot 2022-02-02 at 11 25 30 AM](https://user-images.githubusercontent.com/11971291/152216221-864d4f7f-5d39-476c-86c9-568b16830f14.png) | ![Screen Shot 2022-02-02 at 11 25 40 AM](https://user-images.githubusercontent.com/11971291/152216263-ccc83206-9bbf-4197-a85b-3660ba240456.png) |
| ![Screen Shot 2022-02-02 at 11 27 05 AM](https://user-images.githubusercontent.com/11971291/152216301-b129b025-bf89-467b-8f13-ab40c807ca40.png) | ![Screen Shot 2022-02-02 at 11 26 54 AM](https://user-images.githubusercontent.com/11971291/152216323-5f5c4644-75bb-4255-887a-944bf1f98d13.png) |
| …

Updated spacing to match designs

---

app/screens/VerificationStatusScreen/VerificationStatusScreen.tsx

"face any problems" to "have any problems"

Edited text

---

app/components/ApprovalControls/ApprovalControls.styles.ts
app/components/ApprovalControls/ApprovalControls.tsx
app/store/slices/credentialFoyer.ts
app/types/digitalcredentials.d.ts
package-lock.json
package.json

PT Story - https://www.pivotaltracker.com/story/show/181209190
- Duplication logic compares all fields excluding `issuanceDate` and `proof`
- Credential approval controls give users options on how to proceed with duplicate credentials

Updated duplicate credential handling

---

app/screens/HomeScreen/HomeScreen.tsx
app/styles/mixins.ts

adds backgrounds to swipe row

---

app/screens/HomeScreen/HomeScreen.tsx

Fix swipe to delete modal text

---

app/navigation/SetupNavigation/SetupNavigation.styles.tsx

Centered start screen title

---

app/screens/CredentialScreen/CredentialScreen.tsx
app/screens/DebugScreen/DebugScreen.tsx

Updated debug menu item to details

---

app/navigation/SettingsNavigation/SettingsNavigation.tsx

Removed add credential dev settings item

---

app/lib/request.ts
package-lock.json
package.json

PT Story - https://www.pivotaltracker.com/story/show/181613415

Added support for decoding HTML entities within credentials

---

.github/workflows/build-android.yml
.github/workflows/build-ios.yml
package-lock.json
package.json

I used [these](https://ariya.io/2020/12/continuous-integration-for-react-native-apps-with-github-actions) github actions to build the android and ios targets. At the very least this confirms that npm packages installs and that the app builds

GitHub actions to compile ios and android

---

app/lib/documentLoader.ts
app/types/digitalcredentials.d.ts
package-lock.json
package.json

Add support for OpenBadges v3 context.

---

app/data/issuerDid.ts

Adding TU Munich as discussed in the TWG Meeting @jfelixh

Adding TUM to Issuer Registry

---

app/components/CredentialCard/CredentialCard.tsx
app/components/CredentialCard/DefaultCredentialCard.tsx
app/model/index.ts
app/types/credential.ts

Add support for achievement term.

---

android/app/src/main/AndroidManifest.xml
app/data/issuerAuth.ts
app/lib/request.ts

- tested on both platforms in debug build config (further setup is necessary for release config)
- only accounts listed in the google console are allowed to log in ATM because the project is not public
- code formatting might be off because `prettier` is not used in the project (sorry)

feat: add login with google

---

app/screens/PublicLinkScreen/PublicLinkScreen.tsx

PT Story: https://www.pivotaltracker.com/story/show/182885409

Removed credential id from LinkedIn share link

---

app/screens/ShareCredentialScreen/ShareCredentialScreen.tsx
app/screens/ShareHomeScreen/ShareHomeScreen.tsx

PT Story: https://www.pivotaltracker.com/story/show/182903681

Updated share icon

---

app/components/CredentialCard/CredentialCard.styles.tsx
app/components/CredentialCard/DefaultCredentialCard.tsx
app/components/CredentialItem/CredentialItem.d.ts
app/components/CredentialItem/CredentialItem.tsx
app/components/CredentialStatusBadges/CredentialStatusBadges.d.ts
app/components/CredentialStatusBadges/CredentialStatusBadges.styles.ts
app/components/CredentialStatusBadges/CredentialStatusBadges.tsx
app/components/StatusBadge/StatusBadge.d.ts
app/components/StatusBadge/StatusBadge.styles.ts
app/components/StatusBadge/StatusBadge.tsx
app/components/index.ts
app/screens/HomeScreen/HomeScreen.tsx
package-lock.json

PT Story: https://www.pivotaltracker.com/story/show/182337054

Added credential share status badge

---

app/navigation/SetupNavigation/SetupNavigation.tsx
app/screens/ApproveCredentialScreen/ApproveCredentialScreen.tsx
app/screens/CredentialScreen/CredentialScreen.styles.tsx
app/screens/CredentialScreen/CredentialScreen.tsx

* [Change 3 dot menu "Details" to "View Source"](https://www.pivotaltracker.com/story/show/182489990)
* [Update minimum length password to 6 from 10](https://www.pivotaltracker.com/story/show/182538368)
* [Remove accept/decline credential on credential preview screen](https://www.pivotaltracker.com/story/show/182834985)

Update UI (minor)

---

app/navigation/CredentialNavigation/CredentialNavigation.tsx
app/screens/ShareCredentialScreen/ShareCredentialScreen.tsx

Added share confirm modals

---

app/components/CredentialItem/CredentialItem.styles.tsx
app/components/CredentialItem/CredentialItem.tsx
app/components/CredentialStatusBadges/CredentialStatusBadges.tsx
app/components/VerificationCard/VerificationCard.tsx
app/hooks/useVerifyCredential.ts
app/lib/cache.ts
app/navigation/SettingsNavigation/SettingsNavigation.d.ts
app/navigation/SettingsNavigation/SettingsNavigation.tsx
app/screens/ApproveCredentialScreen/ApproveCredentialScreen.tsx
app/screens/CredentialScreen/CredentialScreen.tsx
app/screens/DeveloperScreen/DeveloperScreen.d.ts
app/screens/DeveloperScreen/DeveloperScreen.styles.ts
app/screens/DeveloperScreen/DeveloperScreen.tsx
app/screens/PublicLinkScreen/PublicLinkScreen.tsx
app/screens/ShareCredentialScreen/ShareCredentialScreen.tsx
app/screens/index.ts
app/styles/colors.ts
app/styles/theme.d.ts
app/styles/theme.ts

PT Stories:
* [The Home screen should display verification status for each credential; with cache for updating](https://www.pivotaltracker.com/story/show/182885792)
* [Remove "Add Credential (DEV)" from About menu?](https://www.pivotaltracker.com/story/show/183135344)
To see the credentials re-verify, you can clear the cache by navigating to the hidden developer menu:
Settings > About > Tap build number

Added verification status badge

---

app/navigation/SetupNavigation/SetupNavigation.tsx
app/screens/ApproveCredentialScreen/ApproveCredentialScreen.tsx
app/screens/ShareCredentialScreen/ShareCredentialScreen.tsx
app/store/selectorFactories/makeSelectProfileForPendingCredentials.ts

Review/merge after #209 has been merged into `main`
PT Stories:
* https://www.pivotaltracker.com/story/show/183145500
* https://www.pivotaltracker.com/story/show/183146547
* https://www.pivotaltracker.com/story/show/182834985

UI updates

---

app/screens/ShareCredentialScreen/ShareCredentialScreen.tsx

Review/merge after #210 has been merged into `main`
PT Story: https://www.pivotaltracker.com/story/show/183090862

Added credential id to LinkedIn share link

---

app/components/BackupItemModal/BackupItemModal.tsx

Prerequisite merge: #211
PT Story: https://www.pivotaltracker.com/story/show/183135084

Fixed backup profile loader

---

app/components/CredentialCard/CredentialCard.d.ts
app/components/CredentialCard/CredentialCard.styles.tsx
app/components/CredentialCard/CredentialCard.tsx
app/components/CredentialCard/DefaultCredentialCard.tsx
app/components/VerificationCard/VerificationCard.tsx
app/hooks/useVerifyCredential.ts
app/lib/issuer.ts
app/navigation/AddCredentialNavigation/AddCredentialNavigation.d.ts
app/navigation/AddCredentialNavigation/AddCredentialNavigation.tsx
app/navigation/CredentialNavigation/CredentialNavigation.d.tsx
app/navigation/CredentialNavigation/CredentialNavigation.tsx
app/navigation/index.ts
app/screens/ApproveCredentialScreen/ApproveCredentialScreen.tsx
app/screens/CredentialScreen/CredentialScreen.tsx
app/screens/IssuerInfoScreen/IssuerInfoScreen.d.ts
app/screens/IssuerInfoScreen/IssuerInfoScreen.styles.ts
app/screens/IssuerInfoScreen/IssuerInfoScreen.tsx
app/screens/index.ts

PT Story: https://www.pivotaltracker.com/story/show/183146640

Added issuer info button

---

app/lib/biometrics.ts
app/navigation/SettingsNavigation/SettingsNavigation.d.ts
app/navigation/SettingsNavigation/SettingsNavigation.styles.tsx
app/navigation/SettingsNavigation/SettingsNavigation.tsx
app/navigation/SetupNavigation/SetupNavigation.tsx
app/screens/LoginScreen/LoginScreen.tsx
app/store/slices/wallet.ts

PT Stories
* https://www.pivotaltracker.com/story/show/183275628
* https://www.pivotaltracker.com/story/show/183275579
* https://www.pivotaltracker.com/story/show/183275620

Fixed biometric auth logic

---

app/screens/ManageProfilesScreen/ManageProfilesScreen.styles.tsx
app/screens/ManageProfilesScreen/ManageProfilesScreen.tsx

PT Story: https://www.pivotaltracker.com/story/show/183275648

Fixed profile overflow styling

---

app/screens/PublicLinkScreen/PublicLinkScreen.styles.tsx
app/screens/PublicLinkScreen/PublicLinkScreen.tsx
app/screens/ShareSelectionScreen/ShareSelectionScreen.styles.ts
app/screens/ShareSelectionScreen/ShareSelectionScreen.tsx

PT Story: https://www.pivotaltracker.com/story/show/183146623

Added share modal FAQ links

---

app/screens/PublicLinkScreen/PublicLinkScreen.styles.tsx
app/screens/PublicLinkScreen/PublicLinkScreen.tsx
app/screens/ShareSelectionScreen/ShareSelectionScreen.styles.ts
app/screens/ShareSelectionScreen/ShareSelectionScreen.tsx

PT Story: https://www.pivotaltracker.com/story/show/183315136

Added "Beta" to screen titles

---

app/components/CredentialCard/DefaultCredentialCard.tsx
app/types/credential.ts

PT Story: https://www.pivotaltracker.com/story/show/182901243

Added criteria field

---

app/components/CredentialCard/DefaultCredentialCard.tsx
app/types/credential.ts

PT Story: https://www.pivotaltracker.com/story/show/183343180

Updated criteria field reference

---

app/components/ConfirmModal/ConfirmModal.style.tsx
app/components/CredentialCard/DefaultCredentialCard.tsx
app/components/PasswordInput/PasswordInput.tsx
app/components/ProfileItem/ProfileItem.tsx
app/screens/AddScreen/AddScreen.tsx
app/screens/HomeScreen/HomeScreen.tsx
app/screens/ManageProfilesScreen/ManageProfilesScreen.tsx
app/screens/ShareHomeScreen/ShareHomeScreen.tsx
app/styles/mixins.ts
app/types/credential.ts

PT Stories: 
* https://www.pivotaltracker.com/story/show/183090931
* https://www.pivotaltracker.com/story/show/183342650

Updated component styles

---

app/lib/share.ts
app/screens/PublicLinkScreen/PublicLinkScreen.tsx

PT Story: https://www.pivotaltracker.com/story/show/182337073

Fixed LinkedIn share URL

---

app/screens/PublicLinkScreen/PublicLinkScreen.tsx

PT Story: https://www.pivotaltracker.com/story/show/183154324

Fixed linked share warning modal

---

app/lib/error.ts
app/model/profile.ts

Ensure #228 is merged first.
PT Story: https://www.pivotaltracker.com/story/show/183211347

Updated delete last profile error message

---

app/screens/PublicLinkScreen/PublicLinkScreen.tsx

Ensure #230 is merged first.
PT Story: https://www.pivotaltracker.com/story/show/183090939
The text is now selectable.

Updated public link url field

---

app/screens/ApproveCredentialsScreen/ApproveCredentialsScreen.tsx

PT Story: https://www.pivotaltracker.com/story/show/183083150

Updated add to profile text

---

app/components/ImportFileModal/ImportFileModal.tsx
app/lib/error.ts
app/screens/ApproveCredentialsScreen/ApproveCredentialsScreen.tsx

PT Story: https://www.pivotaltracker.com/story/show/183091050

Fixed cancel restore wallet behavior

---

app/lib/share.ts

PT Story: https://www.pivotaltracker.com/story/show/183468396

Removed double encoding for LinkedIn URL

---

app/components/BackupItemModal/BackupItemModal.tsx

PT Story: https://www.pivotaltracker.com/story/show/183476029

Fixed backup modal password checkbox

---

app/data/issuerDid.ts

Updating TUM & HPI Issuer DIDs

---

app/components/GlobalErrorModal/GlobalErrorModal.tsx
app/components/index.ts
app/hooks/useAppLoading.ts
app/lib/registry.ts
app/lib/validate.ts
app/navigation/AppNavigation/AppNavigation.tsx
app/navigation/RootNavigation/RootNavigation.tsx
app/store/slices/wallet.ts

Updated iteration of #177
PT Story: https://www.pivotaltracker.com/story/show/183583326

Added remote registry loading logic

---

app/components/VerificationStatusCard/VerificationStatusCard.styles.ts
app/components/VerificationStatusCard/VerificationStatusCard.tsx
app/hooks/useVerifyCredential.ts
app/lib/validate.ts
app/mock/revokedCredential.ts
app/screens/DeveloperScreen/DeveloperScreen.tsx
app/types/credential.ts

- An exception is now thrown when the verify response does not contain a log value
- The verification status card now displays the error message (if present) in place of the checkmark list
See https://github.com/digitalcredentials/vc/issues/6 for context
PT Story: https://www.pivotaltracker.com/story/show/182811038

Updated verify credential error handling logic

---

app/components/BulletList/BulletList.d.ts
app/components/BulletList/BulletList.style.ts
app/components/BulletList/BulletList.tsx
app/components/CredentialCard/CredentialCard.styles.tsx
app/components/CredentialCard/DefaultCredentialCard.tsx
app/components/CredentialStatusBadges/CredentialStatusBadges.tsx
app/components/VerificationStatusCard/VerificationStatusCard.d.ts
app/components/VerificationStatusCard/VerificationStatusCard.styles.ts
app/components/VerificationStatusCard/VerificationStatusCard.tsx
app/components/index.ts
app/lib/import.ts
app/lib/share.ts
app/screens/DetailsScreen/DetailsScreen.tsx
app/screens/IssuerInfoScreen/IssuerInfoScreen.d.ts
app/screens/IssuerInfoScreen/IssuerInfoScreen.styles.ts
app/screens/IssuerInfoScreen/IssuerInfoScreen.tsx

PT Stories:
* https://www.pivotaltracker.com/story/show/183642599
* https://www.pivotaltracker.com/story/show/183642685
* https://www.pivotaltracker.com/story/show/183642509

Updated verification status card with issuer registries

---

config/registryCollections.json

PT Story: https://www.pivotaltracker.com/story/show/183702501

Update registry names

---

app/components/ImportFileModal/ImportFileModal.tsx
app/lib/constants.ts
app/lib/decode.ts
app/lib/encode.ts
app/lib/error.ts
app/lib/shareIntent.ts
app/lib/verifiableObject.ts
app/navigation/AppNavigation/AppNavigation.tsx
app/screens/AddScreen/AddScreen.styles.tsx
app/screens/AddScreen/AddScreen.tsx
app/screens/ManageProfilesScreen/ManageProfilesScreen.tsx
app/styles/colorScheme.ts
app/styles/theme/index.d.ts
app/styles/theme/themes/darkTheme.ts
app/styles/theme/themes/lightTheme.ts
patches/react-native-paper+4.12.4.patch

Issues: 
* #250 
* #249
PT Stories:
* https://www.pivotaltracker.com/story/show/183158668
* https://www.pivotaltracker.com/story/show/183158675
* https://www.pivotaltracker.com/story/show/183701290
A credential can now be added through a **supported format** containing the any of the specified **content types**.
**Supported Formats**:
- QR Code
- URL QR Code
- URL
- File
- Raw Text
**Content Types**:
- JSON
- VPQR
| Add Screen | Active |
| --- | --- |
| ![Simulator Screen Shot - iPhone 13 - 2022-11-04 at 16 14 45](https://user-images.githubusercontent.com/11971291/200082870-2338796d-b71d-4cf0-92d7-f8749309c81f.png) | ![Simulator Screen Shot - iPhone 13 - 2022-11-04 at 16 15 21](https://user-images.githubusercontent.com/11971291/200082880-fb28ad4c-616a-4934-9b06-0c7ec9731573.png) |

Update add credential screen

---

app/lib/import.ts
app/lib/lockedWallet.ts
app/types/wallet.ts
package-lock.json
package.json

It looks like this issue was RN community wide as of a couple days ago. 
See issue: https://github.com/facebook/react-native/issues/35210

Fix Android build error

---

install-linux.md

Have fixed the installation docs and make it more beginner-friendly and added some specific versions which I felt as an issue when I was setting up this repository.

fix: installation docs

---

app/components/VerificationStatusCard/VerificationStatusCard.tsx

PT Story: https://www.pivotaltracker.com/story/show/183701869

Update issuer verification status card text

---

android/app/build.gradle
app/components/CredentialStatusBadges/CredentialStatusBadges.tsx
app/lib/cache.ts
app/lib/credentialRequest.ts
app/lib/present.ts
app/lib/shareRequest.tsx
app/lib/url.ts
app/lib/verifierPlus.ts
app/screens/PublicLinkScreen/PublicLinkScreen.tsx
ios/eduWallet.xcodeproj/project.pbxproj
package-lock.json
package.json

Send a delete/unshare request to vplus on button press.

---

app/lib/import.ts
app/navigation/SetupNavigation/SetupNavigation.tsx
app/store/slices/wallet.ts

The wallet can now be initialized with an existing profile or wallet file.
PT Story: https://www.pivotaltracker.com/story/show/183960807

Update custom setup logic

---

app/components/CredentialItem/CredentialItem.tsx
app/navigation/SettingsNavigation/SettingsNavigation.tsx
app/screens/ProfileSelectionScreen/ProfileSelectionScreen.tsx

PT Story: https://www.pivotaltracker.com/story/show/183960228

Update chevron style

---

app/screens/ApproveCredentialsScreen/ApproveCredentialsScreen.tsx

Fix "Accept All" button logic

---

app/lib/present.ts

Updates the credential share format back to JSON (previously VPQR text)
PT Stories:
* https://www.pivotaltracker.com/story/show/183960294
* https://www.pivotaltracker.com/story/show/183962831

Update credential share format

---

app/components/ProfileItem/ProfileItem.tsx
app/hooks/useAppLoading.ts
app/lib/export.ts
app/lib/present.ts
app/lib/shareData.ts
app/navigation/SettingsNavigation/SettingsNavigation.d.ts
app/screens/DeveloperScreen/DeveloperScreen.styles.ts
app/screens/DeveloperScreen/DeveloperScreen.tsx
app/screens/ViewSourceScreen/ViewSourceScreen.d.ts
app/screens/ViewSourceScreen/ViewSourceScreen.styles.ts
app/screens/ViewSourceScreen/ViewSourceScreen.tsx
app/screens/index.ts
app/styles/fonts.ts
app/styles/theme/themes/darkTheme.ts
app/styles/theme/themes/lightTheme.ts
ios/Podfile.lock
package-lock.json
package.json

PT Story: https://www.pivotaltracker.com/story/show/183642435

Add developer log screen

---

app/components/PasswordForm/PasswordForm.tsx

Fix input theme style

---

app/navigation/SetupNavigation/SetupNavigation.tsx

Fix custom setup details "back route"

---

app/components/ConfirmModal/ConfirmModal.d.ts
app/hooks/useVerifyCredential.ts
app/screens/PublicLinkScreen/PublicLinkScreen.tsx
app/screens/ShareHomeScreen/ShareHomeScreen.tsx

Related Issues:
* #297 
* #298

Add warning modals

---

app/styles/theme/themes/lightTheme.ts

Fixes issue #309
Now a darker shade of blue (matching the accent color for the rest of the light theme)

Update light theme switch color

---

app/navigation/SetupNavigation/SetupNavigation.tsx

Fix Android button group styling

---

android/app/src/main/AndroidManifest.xml

Fixes #345 
Solution found in article:
https://stackoverflow.com/questions/19829507/android-java-lang-securityexception-permission-denial-starting-intent

Fix Android oauth redirect

---

app/screens/PublicLinkScreen/PublicLinkScreen.tsx
app/screens/ShareHomeScreen/ShareHomeScreen.tsx

Updates the warning modals to inform the user that public links automatically expire in 1 year.

Public link text

---

app/lib/decode.ts
app/lib/exchanges.ts
app/lib/validate.ts
app/lib/verifiableObject.ts

Add diagnostics, allow security loader to load from web.

---

app/components/ImportFileModal/ImportFileModal.tsx
app/navigation/SetupNavigation/SetupNavigation.tsx

When users first open app, now they will see the "Quick Setup" button to click onscreen. All code related to the Custom Setup has been removed.
Tag on commit: `custom-setup-removed`

Removed Custom Setup Option

---

app/components/PasswordForm/PasswordForm.tsx

Project Board Story: https://github.com/orgs/digitalcredentials/projects/14/views/1?pane=issue&itemId=33466403

Updated warning text 

---

app/lib/publicLink.ts

Issue: https://github.com/digitalcredentials/learner-credential-wallet/issues/365
Fixed Issue Date and Expiration Date in LinkedIn Certification Fields

Issue & Expiration Dates fixed

---

app/lib/credentialDisplay/openBadgeCredential.tsx
app/lib/credentialDisplay/shared/components/CardDetail.tsx
package-lock.json
package.json
tsconfig.json

Resolves Issue [#456](https://github.com/orgs/digitalcredentials/projects/14/views/1?pane=issue&itemId=33793354)
Adds markdown support, and applies it to the Criteria.Narrative section.

Add Markdown Support for Criteria.Narrative - Issue #456

---

app/lib/credentialDisplay/shared/components/CardDetail.tsx

This PR fixes colors for ordered lists and unordered lists in markdown.

fixes markdown list colors

---

app/styles/mixins.ts

Issue: https://github.com/digitalcredentials/learner-credential-wallet/issues/467
reversed changes from fixing LinkedIn button, make new request for LinkedIn button @kayaelle

fixed copy button

---

app/lib/credentialDisplay/index.ts
app/lib/credentialDisplay/openBadgeCredential.tsx

Github Board: https://github.com/digitalcredentials/learner-credential-wallet/issues/478
Title now matches in both Home view and Credential Preview

issue #478 - Credential Preview & Home title

---

app/lib/publicLink.ts

Do not share certId to LI.

---

app/lib/credentialDisplay/openBadgeCredential.tsx
app/lib/credentialDisplay/shared/styles.ts

Issuance and Expiration dates are now in a row
Issue: https://github.com/digitalcredentials/learner-credential-wallet/issues/486

Moved Issuance Date and Expiration Date to be in a row together

---

app/lib/credentialDisplay/openBadgeCredential.tsx
app/lib/credentialDisplay/shared/components/CardDetail.tsx
app/lib/credentialDisplay/shared/styles.ts
ios/Podfile.lock
ios/eduWallet.xcodeproj/project.pbxproj

Issue: https://github.com/digitalcredentials/learner-credential-wallet/issues/485

Achievement Type now listed underneath Credential Title/Name (#485)

---

app/lib/publicLink.ts
app/screens/QRScreen/QRScreen.tsx

Project Board: https://github.com/digitalcredentials/learner-credential-wallet/issues/338
This commit only covers iOS currently

added pop up alert for when QR doesn't have camera access

---

app/lib/credentialDisplay/openBadgeCredential.tsx

Issue: https://github.com/digitalcredentials/learner-credential-wallet/issues/512

removed duplicate Credential Type label below the dates

---

app/lib/credentialDisplay/openBadgeCredential.tsx
app/lib/credentialDisplay/verifiableCredential.tsx

Issue: https://github.com/digitalcredentials/learner-credential-wallet/issues/511

Replace "Subject Name" to "Issued To"

---

app/hooks/useVerifyCredential.ts
package-lock.json
package.json

Issue: https://github.com/digitalcredentials/learner-credential-wallet/issues/314
Used library: https://github.com/digitalcredentials/lru-memoize#usage
NOTE: Unsure how to test as instructions in issue seem out dated and we are unable to create our own certificates at this time. @dmitrizagidulin @kayaelle

Component Caching -> Time Caching

---

app/lib/registerWallet.ts
app/navigation/SettingsNavigation/SettingsNavigation.tsx
app/navigation/SetupNavigation/SetupNavigation.d.tsx
app/navigation/SetupNavigation/SetupNavigation.styles.tsx
app/navigation/SetupNavigation/SetupNavigation.tsx
ios/eduWallet.xcodeproj/project.pbxproj

Resolves Issue 457 regarding the wallet registration. https://github.com/digitalcredentials/learner-credential-wallet/issues/457

Register Wallet installation step added (issue #457)

---

app/lib/registerWallet.ts
ios/eduWallet/wallet.entitlements

Partly addresses issue https://github.com/digitalcredentials/learner-credential-wallet/issues/505

Associate LCW with lcw.app domain.

---

android/app/src/main/AndroidManifest.xml

Partly addresses https://github.com/digitalcredentials/learner-credential-wallet/issues/505

Add Android intent for app link.

---

app/screens/PublicLinkScreen/PublicLinkScreen.tsx
app/screens/ShareHomeScreen/ShareHomeScreen.tsx

Issue: https://github.com/digitalcredentials/learner-credential-wallet/issues/517
Removed all 3 (Beta) Titles per request in meeting

(Issue #517) Removed (Beta) in titles

---

.eslintrc.json
.github/workflows/build-android.yml
.github/workflows/build-ios.yml
.github/workflows/lint-project.yml
app/screens/PublicLinkScreen/PublicLinkScreen.tsx
ios/Podfile.lock
package-lock.json
package.json

updated workflows and Podfile.lock and package-lock.json to working build files

Updated github workflow files node version

---

README.md

@dmitrizagidulin I think we need to go through the README and do a cleanup before we merge this as there's some out of date information that could lead future developers wrong. In my opinion adding info to the Wiki is better but if you want to keep it in the README that's fine. Either way we should cleanup :)

updated readme to point to troubleshooting page

---

app/config/index.ts
app/lib/deepLink.ts

Part of refactoring / cleanup for OWF.

Move deep link schemes to config.

---

package.json

Fixes issue https://github.com/digitalcredentials/learner-credential-wallet/issues/526

Update to latest Bitstring Status List dependency.

---

android/app/build.gradle
android/app/src/main/java/app/lcw/LCWReceiveModule.java
android/app/src/main/java/app/lcw/LCWReceivePackage.java
android/app/src/main/java/app/lcw/MainApplication.java
app/hooks/index.ts
app/hooks/useLCWReceiveModule.tsx
app/navigation/AppNavigation/AppNavigation.tsx

Was causing crash in app store beta.

Revert Java rename.

---

app/mock/credential.ts

To address broken creds on LCW

Update mock credential

---

app/lib/credentialDisplay/openBadgeCredential.tsx

Wrap credential name in header

---

android/build.gradle
app/lib/registerWallet.ts

Attempt to open Register Wallet page regardless of canOpenURL.

---

app/screens/PublicLinkScreen/PublicLinkScreen.tsx

Fixes issue #518 (along with fix https://github.com/digitalcredentials/docs/commit/55b9c127213f71a577f8687977c3b4eed4433a55 )

Fix PDF generation Share call.

---

.github/workflows/build-ios.yml
app.json
app/navigation/ExchangeCredentialsNavigation/ExchangeCredentialsNavigation.d.ts

Fix Expo app.json version numbers, fix CHAPI import.

---

app/screens/PublicLinkScreen/PublicLinkScreen.tsx
app/types/pdf.ts

Fix filePath for renderMethod PDF generation

---

app/screens/PublicLinkScreen/PublicLinkScreen.tsx

Related to https://github.com/openwallet-foundation-labs/learner-credential-wallet/issues/650

Add linkedin functionality to pdf export

---

app/screens/PublicLinkScreen/PublicLinkScreen.tsx

Improve copy and user flow for export to PDF

---

app/lib/decode.ts
config.ts
test/decode.test.ts
tsconfig.json

627 deep linking for qr codes

---

app/model/DatabaseAccess.ts

Fixes issue https://github.com/openwallet-foundation-labs/learner-credential-wallet/issues/695

Enforce key length on wallet init

---

app/lib/import.ts
test/import.test.ts

Replaces #707 
Resolves https://github.com/openwallet-foundation-labs/learner-credential-wallet/issues/649

Import badges + tests

---

app/lib/import.ts
app/types/import.ts
package-lock.json
package.json
test/import.test.ts

Fixes badge import issue, also ensures that credentials in .txt files can continue to be imported.
WRT https://github.com/openwallet-foundation-labs/learner-credential-wallet/issues/649

Use RN buffer library to ID png badges

---

app/screens/ExchangeCredentials/ExchangeCredentials.tsx

Allows iOS users to select credentials for Verifiable presentation requests for cold starts (when app is closed). Fixes https://github.com/openwallet-foundation-labs/learner-credential-wallet/issues/765

fix for iOS bug for verifiable presentation request

---

app/lib/exchanges.ts

Fixes https://github.com/openwallet-foundation-labs/learner-credential-wallet/issues/781

Fix back arrow for credential selection request
