openwallet-foundation-labs/learner-credential-wallet

app/navigation/HomeNavigation/HomeNavigation.d.tsx, app/navigation/HomeNavigation/HomeNavigation.styles.ts, app/navigation/HomeNavigation/HomeNavigation.tsx, package-lock.json, package.json
PT Story
https://www.pivotaltracker.com/story/show/179830413
This PR replaces the bottom material tabs library with native bottom tabs.
This is to use the property `unmountOnBlur` to reset the route state when navigating.
=> Fixed persisting navigation route state

App.tsx, app/hooks/index.ts, app/hooks/useAppLoading.ts, app/navigation/AppNavigation/AppNavigation.tsx, app/navigation/index.ts, app/screens/ApproveCredentialsScreen/ApproveCredentialsScreen.tsx, app/screens/CredentialScreen/CredentialScreen.tsx, app/screens/HomeScreen/HomeScreen.tsx
This addresses issue #69 and bugs related to the "white screen stall" seen on app re-install.
PT Story: https://www.pivotaltracker.com/story/show/180188953
Some insight on the cause of the issues:
This bug was introduced as a result of the changes in PR #68, but was not discovered until later. The state initialization logic was refactored incorrectly, preventing state-database synchronization. This explains the missing credentials. Specifically, the DID document is never retrieved, resulting in a fatal error during credential validation on the preview screen. 
SecureStore items aren't removed when the app is deleted, so if a key (from a previous install) exists, the database status is initially interpreted as unlocked but not initialized. This combination produces undefined routing …
=> Refactored route and loading logic

app/lib/validate.ts, app/store/slices/credentialFoyer.ts
Fixes #80.
Not all credentials contain the `id` attribute.
The logic has been updated to use the `proofValue` to differentiate credentials.
=> Fixed duplicate credential logic

app/screens/QRScreen/QRScreen.tsx, package-lock.json, package.json
See issue #97
This update detects a deeplink in a QR code and redirects to the AddScreen for the deeplink to be handled similarly to when a deeplink is clicked outside the app.
I don't think this is ready for merging. A few notes:
The deeplink needs to specify at least `vc_request_url`, `issuer` and `challenge` as params.
Currently an deeplink without the correct parameters will redirect to the add screen without any error (this probably also applies to links clicked outside the app).
The overall flow from adding a credential this way is different from adding a CBOR-LD QR Code, since the user will be redirected to an auth flow. I'm assuming that is the intended behavior?
For parsing query parameters I used 'query-string', this was already an indirect dependency.
=> Add logic for handling a deeplink in a QR code

patches/react-native-animated-ellipsis+2.0.0.patch
This resolves the library's current warning:
```
Animated: `useNativeDriver` was not specified. This is a required option and must be explicitly set to `true` or `false`
```
=> Patched react-native-animated-ellipsis

app/lib/request.ts
Fixes #122 
Wrapping the `verifyCredential` method in a try/catch, allows the credential to still be received if the method itself were to throw an error.
_The error will be passed to the console as a warning for now._
=> Fixed verification error handling

app/data/issuerAuth.ts
This PR adds `email` scope to default OIDC issuer used in DCC Playground
=> adds email scope to playground default oidc issuer

app/hooks/useShareCredentials.ts, app/store/slices/wallet.ts
Fixes #146 
When the user clicks the "Take Me to My Wallet" button the wallet is initialized but the process of generating the DID is started asynchronously. This was causing the `isInitialized` field in the store to be set to true before DID generation was complete. This meant the app transitioned to the Home screen before the DID was generated, causing the exception to be thrown.
This fix ensures the DID generation is completed before transitioning to the home screen.
=> ensure did is created before transition to root navigation

app/components/CredentialCard/CredentialCard.styles.tsx, app/hooks/useRequestCredential.ts, app/lib/parseResponse.ts, app/lib/request.ts, app/lib/verifiableObject.ts, app/screens/AddScreen/AddScreen.tsx
GitHub Issue - #162
PT Story - https://www.pivotaltracker.com/story/show/181662018
- Created the type `VerifiableObject` to identify a response that could be a VC or VP.
- Added lib methods to handle operations for that union type.
- Updated request payload type to support multiple credentials.
=> Updated request logic to receive verifiable presentations 

app/store/slices/wallet.ts
App startup only loaded DIDs and credentials if the wallet was already unlocked upon launching the app. This fix causes the DIDs and Credentials to be loaded when the user unlocks the app if the wallet is locked on launch.
=> load did and credentials when unlocking the wallet

app/components/ConfirmModal/ConfirmModal.tsx, app/screens/ManageProfilesScreen/ManageProfilesScreen.tsx
PT Story: https://www.pivotaltracker.com/story/show/183275565
This PR disables accessibility focus on Android for the `ConfirmModal` component.
_This is temporary fix for the error throw while backing up the wallet. Further investigation should be done to adequately fix the issue._
=> Fixed backup error on Android

android/app/build.gradle, android/app/src/main/AndroidManifest.xml, android/app/src/main/java/app/lcw/LCWReceiveModule.java, android/app/src/main/java/app/lcw/LCWReceivePackage.java, android/app/src/main/java/app/lcw/MainApplication.java, android/build.gradle, app/hooks/index.ts, app/hooks/useLCWReceiveModule.tsx, app/lib/didAuthRequest.ts, app/lib/exchanges.ts, app/navigation/AcceptCredentialsNavigation/AcceptCredentialsNavigation.d.ts, app/navigation/AppNavigation/AppNavigation.tsx, app/screens/ProfileSelectionScreen/ProfileSelectionScreen.tsx, app/types/digitalcredentials.d.ts, patches/react-native-receive-sharing-intent+2.0.0.patch, shim.js
* Rebased version of #271
* Separated CHAPI support logic into separate lib and corresponding hook.
* Replaced `any` types with type definitions
* Some of the changes that support this effort were made by fixing merge conflicts while rebasing. Commit a56134ef1ed599aebb6f78c77440484db5fb1a0b reflects the outlying diff post rebase.
* This does not fix the additional issues mentioned here: https://github.com/digitalcredentials/learner-credential-wallet/pull/271#issuecomment-1323999572_
In theory, #271 and #269 can be closed after this has been merged. Although I suspect additional work will be required to complete CHAPI implementation.
=> [Rebased] fixes iOS build alongside Android CHAPI implementation

app/lib/cache.ts, app/store/slices/wallet.ts
Closes #342
1. Disable dark mode (enabling light mode)
2. Reset the wallet
3. Open the app
→ _Observe light mode setting remaining intact after wallet reset_
=> Update reset method to clear cache

app/screens/PublicLinkScreen/PublicLinkScreen.tsx
Closes #350 
1. Add un-verified credential to wallet
2. Select credential
3. Select three-dot menu in top right
4. Select share
5. Select `Add to LinkedIn Profile`
→  _Observe error modal preventing user from sharing credential._
=> Add un-verified public share credential error

app/lib/credentialDisplay/shared/components/IssuerInfoButton.tsx, app/lib/credentialDisplay/shared/styles.ts, app/screens/AddScreen/AddScreen.tsx
Closes #347
* The input now trims the "add credential" text input
* Issuer names that span multiple lines now wrap correctly
1. Navigate to `Add Credential` screen
2. Paste `https://certificates.cs50.io/85cf5a9d-bbed-40dc-b121-feec19de64b6.json` into text box
3. Add extra whitespace/newline characters
4. Select `Add`
→ _Observe credential correctly parsed from URL containing whitespace_
1. Select added credential from test above
→ _Observe multiline issuer name wraps correctly_
=> Fix credential input and display (small)

app/lib/credentialDisplay/openBadgeCredential.tsx
Subject Name is displayed twice.
=> Remove double display of name in Open Badge

app/screens/PublicLinkScreen/PublicLinkScreen.tsx
Fixes #361 
Two issues here:
1. The loading model was mislabeled to say "Sending Credential(s)" when it should be "Creating Public Link".
2. The modal stalls and the app is unusable.
This second issue is believed to be caused when the modal is displayed and removed with little to no load time in between. 
This has been fixed by adding a brief artificial delay.
=> Fix "Create public link" modal stall issue

ios/Podfile, ios/Podfile.lock, ios/eduWallet.xcodeproj/project.pbxproj, ios/eduWallet/AppDelegate.m, package-lock.json, package.json
The issue was that the xcode workspace was misconfigured.
closes #442
tested by building for simulator; when I tried to create a new wallet, the camera permission alert was presented as expected.
=> fix: ios build error

app/screens/AddScreen/AddScreen.styles.tsx
Changed zIndex of Input box to -1, such that the input box is still clickable and usable but now the add button is clickable on top of it.
Resolves Issue https://github.com/digitalcredentials/learner-credential-wallet/issues/449#issue-1810747006
=> Fix Android 'add' button not clickable

app/styles/mixins.ts
Project Board/Issue: https://github.com/digitalcredentials/learner-credential-wallet/issues/386
Changed from `flex` to `flexGrow` which allows cancel button and Add to LinkedIn button are in a singular line
=> fixed cancel button w/ linkedin share

app/screens/PublicLinkScreen/PublicLinkScreen.tsx
Resolves [Issue 490](https://github.com/digitalcredentials/learner-credential-wallet/issues/490)
"GT Guide" has been replaced with the actual credential name.
=> "Create a public link" displays "GT Guide" onscreen after creating the link. (#490)

app/navigation/SettingsNavigation/SettingsNavigation.styles.tsx, app/navigation/SettingsNavigation/SettingsNavigation.tsx
Now, only the title is bolded on the about page
Resolves [Issue #325](https://github.com/digitalcredentials/learner-credential-wallet/issues/325)
=> Bold Learner Credential Wallet text on about screen #325

android/app/src/main/AndroidManifest.xml, app/hooks/index.ts, app/hooks/useLCWReceiveModule.tsx, app/hooks/useSelectedExchangeCredentials.ts, app/lib/credentialRequest.ts, app/lib/decode.ts, app/lib/deepLink.ts, app/lib/didAuthRequest.ts, app/lib/exchanges.ts, app/lib/globalModalBody.tsx, app/lib/time.ts, app/navigation/AppNavigation/AppNavigation.tsx, app/navigation/ExchangeCredentialsNavigation/ExchangeCredentialsNavigation.d.ts, app/navigation/ExchangeCredentialsNavigation/ExchangeCredentialsNavigation.tsx, app/navigation/RootNavigation/RootNavigation.d.tsx, app/navigation/RootNavigation/RootNavigation.tsx, app/navigation/index.ts, app/screens/ExchangeCredentials/ExchangeCredentials.d.ts, app/screens/ExchangeCredentials/ExchangeCredentials.tsx, app/screens/index.ts, app/store/slices/credentialFoyer.ts, app/types/chapi.ts, app/types/digitalcredentials.d.ts, ios/Podfile.lock, ios/eduWallet/wallet.entitlements, package-lock.json, package.json
This PR implements URL-based CHAPI issuance and presentation. In order to test it, first register LCW with your default mobile browser [here](https://lcw.app/register-wallet). Next, run this app in dev mode and test [issuance](https://vcplayground.org/issuer) and [presentation](https://vcplayground.org/verifier) in DB's VC Playground. Make sure to configure VC-API in the ⚙️ for both flows in order for CHAPI to recognize LCW during wallet selection.
=> Receive and process CHAPI URL event for issuance and presentation

.github/workflows/lint-project.yml, app/components/CredentialItem/CredentialItem.tsx, app/components/MenuItem/MenuItem.tsx, app/hooks/useDynamicStyles.ts, app/lib/credentialDisplay/shared/components/CardImage.tsx, app/lib/credentialDisplay/studentId.tsx, app/lib/dynamicStyles.ts, app/lib/encode.ts, app/lib/encode.unit.test.ts, app/navigation/SettingsNavigation/SettingsNavigation.tsx, app/navigation/SetupNavigation/SetupNavigation.tsx, app/screens/LoginScreen/LoginScreen.tsx, app/screens/ProfileSelectionScreen/ProfileSelectionScreen.tsx, app/screens/RestartScreen/RestartScreen.tsx, package-lock.json, package.json
This adds jest to the repo and the GH action. While Jest isn't really the tool of choice for other parts of the JS ecosystem, in React Native it's the standard.
there's a little todo in app/lib/encode.unit.test.ts that someone more knowledgeable of the code base could answer. I'm a little unsure about why the `encodeQueryParams` function is even needed. If someone could share some deep links that the app works with, that would be helpful.
=> feat: add jest and a simple test

README.md, android/app/src/main/java/app/lcw/MainApplication.java, android/app/src/main/java/app/lcw/WalletEventReceiveModule.java, android/app/src/main/java/app/lcw/WalletReceivePackage.java, app/config/index.ts, app/hooks/index.ts, app/hooks/useWalletReceiveModule.tsx, app/lib/deepLink.ts, app/lib/registerWallet.ts, app/navigation/AppNavigation/AppNavigation.tsx, app/navigation/SettingsNavigation/SettingsNavigation.tsx, app/screens/DeveloperScreen/DeveloperScreen.tsx, app/screens/PublicLinkScreen/PublicLinkScreen.tsx, app/screens/ShareHomeScreen/ShareHomeScreen.tsx, app/screens/VerificationStatusScreen/VerificationStatusScreen.tsx
In preparation for OWF / to make re-branding easier, this PR extracts hardcoded instances of the LCW name and web site into config.
Also, adds a small section in the README on where the config files live.
=> Extract app name to config

app/screens/PublicLinkScreen/PublicLinkScreen.styles.tsx, app/screens/PublicLinkScreen/PublicLinkScreen.tsx
To address https://github.com/digitalcredentials/learner-credential-wallet/issues/500
=> Add text under single share cred screen

.gitignore, app.json, app/navigation/ExchangeCredentialsNavigation/ExchangeCredentialsNavigation.d.ts, disableAndroidFlipper.sh, package.json
* Fix Expo config file to enable publishing to iOS and Google App Store
* Fix CHAPI import statement
* Drop unused `disableFlipper` script.
Addresses issue #606
=> Expo config updates for publishing

app/navigation/SettingsNavigation/SettingsNavigation.tsx
Updated copyright date from 2021-2022 to 2021-2025 on "about" page #760
=> Change copyright year in About screen

app/lib/import.ts
Created PR for #768 
Refactor base64 decoding in readFile function to use TextDecoder for improved UTF-8 string extraction from PNG files
**Before Update:**
**After Update:**
=> 768: Some Credly Badges Fail Verify

app/screens/PublicLinkScreen/PublicLinkScreen.tsx, app/screens/ShareHomeScreen/ShareHomeScreen.tsx
Addresses part of https://github.com/openwallet-foundation-labs/learner-credential-wallet/issues/446. New information here included right above link to the lcw.app FAQ site highlighting more information about public links. PR for the LCW website update is here: https://github.com/digitalcredentials/learner-credential-wallet-site/pull/20
=> Update blurbs about public link expiration

jest.config.coverage.ts
Created PR for #854 
The issue was that the coverage Jest configuration had an incomplete list of packages to transform with Babel. When running npm test, it uses jest.config.ts which includes all necessary packages for transformation. However, when running npm run coverage, it uses jest.config.coverage.ts which was missing several packages, causing transformation issues and test failures which has been updated.
=> Coverage command fix
